# Generated by Django 5.2.4 on 2025-09-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contactmessage_rename_image_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
