# Generated by Django 5.2.4 on 2025-09-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='detail_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='No description'),
            preserve_default=False,
        ),
    ]
