# Generated by Django 5.2.4 on 2025-09-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_image_detail_image_image_detail_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='detail_text',
        ),
        migrations.AddField(
            model_name='image',
            name='caption2',
            field=models.CharField(default='Default Caption', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.ImageField(default='Default Caption', upload_to='image/'),
            preserve_default=False,
        ),
    ]
