# Generated by Django 5.2.4 on 2025-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_image_detail_image_remove_image_detail_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Pics/')),
                ('Caption', models.CharField(max_length=255)),
                ('Caption1', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image1',
        ),
    ]
