# Generated by Django 5.2.4 on 2025-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_pics_remove_image_caption2_remove_image_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('caption', models.CharField(max_length=255)),
                ('caption1', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='pics',
            old_name='Caption',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='pics',
            name='Caption1',
        ),
        migrations.RemoveField(
            model_name='pics',
            name='Image',
        ),
        migrations.AddField(
            model_name='pics',
            name='caption1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pics',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
